### ISSUE TITLE
undefined reference to EthernetWebServer

### ISSUE THREAD

**Issue by psykokwak-com** [khoih-prog/EthernetWebServer#78] opened 2022-12-26 17:17 UTC
### Describe the bug

In multiple files project I have undefined references.

### Steps to Reproduce

Use the multifile project example with "#define USE_NATIVE_ETHERNET true" (because teensy 4.1)

### Expected behavior

Build successful

### Actual behavior

Build error

> MyFile.cpp.o: In function __static_initialization_and_destruction_0
> MyFile.cpp:6: undefined reference to EthernetWebServer  EthernetWebServer(int)
> MyFile.cpp:6: undefined reference to EthernetWebServer  ~EthernetWebServer()

Please ensure to specify the following:

* Arduino IDE version : 1.8.19n
* Board Core Version Teensy 4.1 Teensyduino 1.57
* Contextual information : Simple two files projects : Project.ino, MyFile.h, MyFile.cpp
* Simplest possible steps to reproduce
* Anything that might be relevant in your opinion, such as:
  * Operating system : Windows 11 Pro

Please be educated, civilized and constructive. Disrespective posts against [GitHub Code of Conduct](https://docs.github.com/en/site-policy/github-terms/github-event-code-of-conduct) will be ignored and deleted.

**Comment by khoih-prog** [comment] 2022-12-26 18:40
Hi @psykokwak-com 

Can you try moving the

```cpp
#define USE_NATIVE_ETHERNET true
```

to `multiFileProject.ino`

I'm testing compile OK here

![Selection_248](https://user-images.githubusercontent.com/57012152/209574911-7b0e29f3-4d5f-45a6-a65f-1907c66c6ce0.png)


Beware that the [**multiFileProject**](https://github.com/khoih-prog/EthernetWebServer/tree/master/examples/multiFileProject) is just the very bare and minimal example for it's simplest **demo** purpose, and don't use it for complex use-case, unless you're sure what you're doing.

As you also didn't post the full code or at least the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example), I suggest you 

1. follow the example code, then modify until it breaks and know what the issue is.
2. change to use the better and supportive [**QNEthernet**](https://github.com/ssilverman/QNEthernet), instead of the `NativeEthernet`

Anyway, I'm closing this issue now and won't reopen until you convincingly prove there is a real bug of the library.

Good Luck,

**Closed as completed by khoih-prog** 2022-12-26 18:40 UTC
Labels: Support
