### ISSUE TITLE
Upload speed it's slow

### ISSUE THREAD

**Issue by alextroto** [khoih-prog/EthernetWebServer#40] opened 2021-11-11 16:45 UTC
Hi,
I'm very happy with your library, so far; just one issue: uploadinglarge files it's very slow.
For example a 170KB file it's taking around 30 seconds to upload it.
I'm using ESP32 + WIZ5500 shield on a SPI bus.
I've changed the HTTP_UPLOAD_BUFLEN to 4K and 16K, no visible change on upload speed.
Downloading the file, it's way more faster (around 1 second).
Thank you,
Alex

**Comment by khoih-prog** [comment] 2021-12-20 21:30
Hi,

Without the [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example), no one can duplicate and check if you're doing everything correctly and this is the bug of this library, or something else.

Also keep in mind that this higher-level library depends on so many underlying libraries, such as Ethernet, etc.,  and the uploading speed also depends on your router, Internet bandwidth, etc.

It's better that you try

1. Using ESP32 **WiFi** only and note / compare the uploading speed in **exactly the same testing environment**. Also try in the same local network
2. Try the [**ESP32_FS_EthernetWebServer**)](https://github.com/khoih-prog/EthernetWebServer/tree/master/examples/ESP32_FS_EthernetWebServer) as I see the uploading speed is so good  when accessing within the same network.

I'm closing the issue now and won't reopen until you finish the test and prove this is the issue caused by some bugs of the library.

Good Luck,

**Closed by khoih-prog** 2021-12-20 21:30 UTC
